### ISSUE TITLE
Relative path at php command include and require

### ISSUE THREAD

**Issue by HendrikKoelbel** [PinkFloyded/idea-file-path-autocomplete#9]
The relative path is not inserted at the Php commands include and require when pressing the ctrl and spacebar but only the normal file name.

![unbenannt4](https://user-images.githubusercontent.com/31684940/47970067-c7f5a380-e080-11e8-8b52-688ba9e21634.PNG)
![unbenannt](https://user-images.githubusercontent.com/31684940/47970068-c7f5a380-e080-11e8-9627-e0053bd71813.PNG)
![unbenannt2](https://user-images.githubusercontent.com/31684940/47970069-c7f5a380-e080-11e8-9b3d-c1f6245f640b.PNG)
![unbenannt3](https://user-images.githubusercontent.com/31684940/47970071-c7f5a380-e080-11e8-9be1-e15565dc4b62.PNG)

**Comment by PinkFloyded** [comment]
The auto-complete dropdown with the icons(the second img) is provided by PHPStorm itself.

When you typed `../../includes/` it didn't show header.php, footer.php, test.css and test.js in the drop-down?

**Comment by HendrikKoelbel** [comment]
But it was indicated however one would like to save oneself the way first „../.../includes“ to enter.

That's why I already reported the problem to PHPStorm that the commands "Include and Require" did not allow a relative automatic selection in the drop down menu.  It only ever entered the name of the file.

**Comment by PinkFloyded** [comment]
Got it. 

From the point of view of this plugin, it only autocompletes valid file paths which are absolute or are relative from the current file's directory.

Though, including all the files in the project for auto-completion may be a good feature to add, but PHPStorm (and I suspect WebStorm, Intellij and other distributions) is already doing this. Ideally, this issue is better handled by them as it doesn't make sense to show the dropdown twice.

**Comment by HendrikKoelbel** [comment]
You can see the current problem at the Youtrack issues Site here:
https://youtrack.jetbrains.com/issue/WI-44010?project=WI&c=Type%20Feature

This article was also created by me.
